### PR TITLE
Dsp reader

### PR DESCRIPTION
**Pull request by jochenklar**
This PR adds a dedicated reader for `.dsp` files and fixes some minor bugs in the `ASCIIReader` and the `JCAMPWriter`.

### CODE REVIEW

**Comment by phuang26** [comment]
@jochenklar Can you attach a dsp sample file for testing? or do you know who could provide the sample file? Thank you.

**Comment by jochenklar** [comment]
I also added functionality to process dedicated table identifiers for `XYData`. To be used with: https://github.com/ComPlat/chemotion-converter-client/pull/44.

**Comment by jochenklar** [comment]
@herrdivad has tested it, can be merged

**Review by phuang26 — APPROVED** [review]

**Comment by herrdivad** [comment]
@phuang26 I can see that the dsp Reader is now on the test Server. Thanks for that. But Jochen also commited a GUI Change for this because of XYData Data Class. Can you put it also on the test Server please?

**Pull request merged**
